__include__: [
  ./vg_detection.yml,
]


num_classes: 20


train_dataloader: 
  dataset: 
    img_folder: ./Datasets/3RScan/ObjectDetection20/images/train
    ann_file: ./Datasets/3RScan/ObjectDetection20/coco/train.json


val_dataloader:
  dataset: 
    img_folder: ./Datasets/3RScan/ObjectDetection20/images/val
    ann_file: ./Datasets/3RScan/ObjectDetection20/coco/val.json